env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  indent:
    [
      "off",
      2,
      { "ignoredNodes": ["TemplateLiteral *"],"SwitchCase": 1 },
    ]
  no-var-requires: 0
  prefer-const: 0
  no-mixed-spaces-and-tabs: 0
  "@typescript-eslint/no-unused-vars": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/no-mixed-spaces-and-tabs": 0